### ISSUE TITLE
i18n Navigation plugin bug preventing CKEditor from loading

### ISSUE THREAD

**Issue by juluisz** [johnstray/gs-blog#159] opened 2018-10-04 20:30 UTC
Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at changeUrl (load.php?id=gs-blog&edit_post=b-czytajmy-naszym-dzieciom:169)
    at HTMLDocument.<anonymous> (load.php?id=gs-blog&edit_post=b-czytajmy-naszym-dzieciom:233)
    at n (jquery.min.js?v=1.7.1:2)
    at Object.fireWith (jquery.min.js?v=1.7.1:2)
    at Function.ready (jquery.min.js?v=1.7.1:2)
    at HTMLDocument.B (jquery.min.js?v=1.7.1:2)

**Comment by johnstray** [comment] 2018-10-05 00:44
What versions of GSBlog and GetSimple does this error appear in?

**Comment by juluisz** [comment] 2018-10-05 06:18
SERWER1
WORKING : 
GetSimple CMS – Version 3.3.2
Version 3.4.4 — Author: John Stray
http://dnizambrowa.zambrowiacy.pl/test.php  - wersion php

SERWER2
NO WORKING:
Version 3.3.15 - GS
Version 3.4.4 — Author: John Stray
http://biblioteka.mokzambrow.pl/test.php - PHP WERSION

In serwer 2 i have 3-4 get simple diferent wersion and no working. i dont see CKDEDITOR in GSBlog
CDEDITOR in normal post working.

**Comment by johnstray** [comment] 2018-10-05 07:35
This is a JavaScript error, not related to PHP. I am unable to reproduce this error as yet (GS 3.3.13, GSBlog 3.4.4).

Could you please load the page where this error happens into your browser, then Right click -> View source, Copy and Paste into txt document and attach here. Thanks

**Comment by juluisz** [comment] 2018-10-05 10:57
[strona.txt](https://github.com/johnstray/gs-blog/files/2449991/strona.txt)
![przechwytywanie](https://user-images.githubusercontent.com/16400418/46531563-f7f13180-c89d-11e8-95ef-5272fbe77b60.JPG)

Ithink is loading jquery 1.7.1 but in good page loading 1.8.1 ??????

**Comment by johnstray** [comment] 2018-10-05 12:02
Ok, it looks like this issue is actually caused by another plugin that you have installed. The line in the code that the error is referring to is at the spot where there is a hook (allows functionality of other plugins). This other plugin is using that hook to inject some code to do its thing.

Can you please list all the plugins you have installed and I'll see if I can figure out which of the plugins is causing the issue.

**Comment by juluisz** [comment] 2018-10-05 12:24
![przechwytywanie](https://user-images.githubusercontent.com/16400418/46534998-4e646d00-c8aa-11e8-9b1d-29c1c4568cb5.JPG)

**Comment by juluisz** [comment] 2018-10-05 12:29
I18N - when i deactivate this then i schow CKEDITOR

**Comment by johnstray** [comment] 2018-10-05 13:49
I had a feeling that it would be 'i18n'. I'll have to do a bit of investigation into this to see if the error can be prevented somehow.

Marking this as a compatibility bug.

**Comment by webservsol** [comment] 2019-01-29 21:17
Replace GetSimple CMS jQuery library with the latest 3.3.1 example

`'jquery'            => '3.3.1',`

Found in the admin folder > assets.php

However you'll have another issue with i18n_navigation

`Uncaught TypeError: $(...).size is not a function
`
Yet I didn't find a solution although I replaced `size ` with `length `but this didn't solve the problem.

**Comment by juluisz** [comment] 2019-02-07 07:46
I dont have this file: Found in the admin folder > assets.php

**Comment by johnstray** [comment] 2021-08-26 19:02
For some strange reason, a javascript that was injected by the i18n Navigation plugin was looking for a html element with the `post-id` id attribute. I have made a fix by adding a hidden div with the id set to `post-id` so as to satisfy the needs of the script.

**Closed as completed by johnstray** 2021-08-26 19:02 UTC
Labels: Bug, Compatibility
