### ISSUE TITLE
Links break after save

### ISSUE THREAD

**Issue by roemhildtg** [johnstray/gs-blog#49] opened 2014-10-30 22:18 UTC
Hello,

I'm experiencing some difficulty with the plugin. If I add a hyperlink to a post, save it and check it, it works fine. But if I edit that post with the link, (not modify the link just a part of the post), the link href turns into a "/", example: `<a href="/">link text</a>`

I'm not sure if I have a configuration issue or I'm doing something wrong but maybe you can point me in the right direction. I've downloaded and installed the latest version here http://get-simple.info/extend/plugin/getsimple-blog/810/ and it seems to work fine on my local machine, however, after uploading it to a server off site, this issue starts occurring.

**Comment by johnstray** [comment] 2015-01-27 05:14
Unable to determine the cause of this issue. This won't be fixed.

**Closed by johnstray** 2015-01-27 05:14 UTC
