### ISSUE TITLE
Slow admin page and version check error

### ISSUE THREAD

**Issue by Kyah** [johnstray/gs-blog#50] opened 2015-01-02 10:26 UTC
Hello,

I'm starting to use gs-blog on my fresh get-simple install and I've found 2 minor problems : 
* Each time we try to access the blog admin page, gs-blog version is checked and make the access really slow. Once disabled, everything looks good to me so I'm wondering if this block in 'gs-blog/inc/adminFunctions.php' realy usefull ?  : 
```php
	if(!isset($_GET['update'])) {
		$update = blog_version_check();
		if($update[0] == 'current') {$ucolor = '#308000';}
		elseif($update[0] == 'update') {$ucolor = '#FFA500';}
		elseif($update[0] == 'beta') {$ucolor = '#2B5CB3';}
		else{$ucolor = '#D94136';}
	} else {$ucolor = '#777777';}
```
* Also, there's actually an error with the checked version of gs-blog. In get-simple extend API we got version 3.3.1 but in 'gs-blog.php' you set the actual version to 3.3.0 : 
```php
define('BLOGVERSION','3.3.0');
```

Hope this help you a little, I'll try to be as helpfull as possible :)

**Comment by johnstray** [comment] 2015-01-02 18:19
Hi Kyah, 
Thanks for posting this issue. I think you may have just found one of the causes of the blog being so slow. 

That entire IF statement is actually leftover from when the version would show on the main blog page too, something it doesn't do any more, and is therefore no longer actually used or required. You should be able to safely delete that entire IF statement.

As for the version definition, that's the second time I've uploaded and forgot to change that now. Whoops. Just change it to 3.3.1 and the versionCheck should report accurately.

These fixes plus a couple of others will be released in an update soon. Thanks again for  your feedback. It's greatly appreciated.

**Closed** 2015-01-27 05:12 UTC
Labels: Bug
