### ISSUE TITLE
Error in Blog Post Manager

### ISSUE THREAD

**Issue by pigsound** [johnstray/gs-blog#139] opened 2018-08-05 13:48 UTC
### Expected behaviour
show post input form

### Actual behaviour
empty;
in post options debugger reports:
Fatal error: Uncaught Error: Cannot use string offset as an array in C:\MAMP\htdocs\directory\plugins\gs-blog\class\customFields.php:25 Stack trace: #0 C:\MAMP\htdocs\directory\plugins\gs-blog\inc\manage_custom_fields.php(232): customFields->getCustomFields() #1 C:\MAMP\htdocs\directory\plugins\gs-blog\inc\html\post-editor.php(50): displayCustomFields() #2 C:\MAMP\htdocs\directory\plugins\gs-blog\inc\adminFunctions.php(174): require_once('C:\\MAMP\\htdocs\\...') #3 C:\MAMP\htdocs\directory\plugins\gs-blog\inc\adminFunctions.php(24): editPost() #4 C:\MAMP\htdocs\directory\admin\load.php(39): blog_admin_controller() #5 {main} thrown in C:\MAMP\htdocs\directory\plugins\gs-blog\class\customFields.php on line 25

**Comment by johnstray** [comment] 2018-08-06 03:30
Duplicate of #138

**Closed** 2018-08-06 03:30 UTC
